# This is sample of config file
# Task config
task: "segmentation"

# Running Parameters
parameters:
  work_dir: "./experiments"
  checkpoint: null
  train:
    max_epoch: 30
    device: gpu
    gpu_ids: 0,1
    batch_size: 32
  test:
    device: gpu
    gpu_ids: 0,1
    batch_size: 1
  val:
    device: gpu
    gpu_ids: 0,1
    batch_size: 12

# Mode config
model:
  # If use backbone + head
  backbones:
    name: ResNet18
    in_channels: 3
    max_layer: 4
    pretrain: true
  heads:
    name: PPM
    num_classes: 4
    fc_dim: 512
    deep_sup: false
  # If use model
  # name: UNet

# Dataset config
dataset:
  name: ImageTaskDataset
  input_type: rgb
  use_dims: 3
  train:
    root: ./data/sample/train
    pipelines:
      - name: Resize
        size: 256
      - name: ToTensor
  test:
    root: ./data/sample/test
    pipelines:
      - name: Resize
        size: 256
      - name: ToTensor
  # ``val`` is optional
  # val:
  #   root: ./data/sample/val
  #   pipelines:
  #     - name: Resize
  #       size: 480
  #     - name: ToTensor

# Loss config
loss:
  name: DiceBCELoss
  weight: 1.0

# Evaluation config
evaluation:
  segmentation:
    methods: [pxacc, miou]

# Optimizer config
optimizer:
  name: Adam

# Scheduler config
scheduler:
  name: ExponentialLR
  gamma: 0.95
